image: Ubuntu2204  # образ для сборки

stack: node 18  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - yarn  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

test_script:
  - yarn test --passWithNoTests # скрипт тестирования

deploy_script: # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name melnikonayana
  - git config --global user.email bezotechestvo.yana@gmail.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=build --branch=gh-pages --force --verbose
